# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dataclamp <- function(input) {
    .Call('antfarm_dataclamp', PACKAGE = 'antfarm', input)
}

rcpp_hello <- function(a, b) {
    .Call('antfarm_rcpp_hello', PACKAGE = 'antfarm', a, b)
}

